### ISSUE TITLE
[Issue]: Unable to Flash Controller

### ISSUE THREAD

**Issue by MorleyGarcia** [Santroller/Santroller#150] opened 2024-03-12 03:33 UTC
### Please describe your issue.

Attempted to Configure guitar controller but am encountering an error. I tried Deleting everything from %appdata%/SantrollerConfigurator, but still encounter same issue.
![Capture](https://github.com/Santroller/Santroller/assets/55711914/d01d842e-3819-4caf-9bd7-f03e44373215)

### Version

V10.0.169

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment] 2024-03-12 04:41
This issue is a duplicate of https://github.com/Santroller/Santroller/issues/149, closing

**Closed by sanjay900** 2024-03-12 04:41 UTC
