### ISSUE TITLE
[Issue]: Midi Drums Don't Properly Trigger Tom Inputs

### ISSUE THREAD

**Issue by RobinatorX** [Santroller/Santroller#205] opened 2024-08-02 02:13 UTC
### Please describe your issue.

Every MIDI signal sent to the microcontroller outputs as its respective cymbal instead of the tom associated with it. For example, the yellow tom always activates the yellow cymbal. I've spent enough time pulling my hair out and trying different configurations that I'm not sure what to do now. The mode used is Rock Band Drums and the console type is PS3. I tried a MIDI keyboard as well with the same results.

### Version

v10.1.153

### What operating system are you using?

Mac OS

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment] 2024-08-19 18:47
I suspect I know the cause of this, and will cut a new release when I get back from my holiday

**Comment by sanjay900** [comment] 2024-08-24 01:05
Should be fixed now

**Closed by sanjay900** 2024-08-24 01:05 UTC

**Comment by RobinatorX** [comment] 2024-08-24 01:08
You’re the best. Thanks for your service to this community🫡
